
---
- include_tasks: freebsd.yml
  when: ansible_os_family == "FreeBSD"
  tags:
    - unbound

- include_tasks: ubuntu.yml
  when: ansible_os_family == "Ubuntu"

- include_tasks: centos.yml
  when: ansible_os_family == "CentOS"
  tags:
    - unbound
---
# - hosts: example
#   become: true
#   user: remy
#   connection: ssh 

#   tasks:
 - name: Install apache
   apt: 
     name: {{ item }} 
    state: latest
   with_items:
    - apache2
   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

 - name: Install httpd
   yum: 
     name: {{ item }} 
     state: latest
   with_items:
    - httpd
   when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

 - name: restart apache
   service: 
     name: apache2 
     state: started 
     enabled: yes
   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

 - name: restart httpd
   service: 
     name: httpd 
     state: started 
     enabled: yes
   when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'