---
 - name: Install Apache
   yum: pkg=httpd state=latest

 - name: Install php
   yum: name=php state=present

 - name: Install mysql
   yum: name=mysql state=present
  
 - name: Enable Apache on System Boot
   service: name=httpd enabled=yes

   notify:
   - start apache
   - setup firewalld
   - reload firewalld

