---
 - name: 1. install Apache
   yum: name=httpd state=present

 - name: 2. install PHP module for Apache
   yum: name=php state=present

 - name: 2. install MYSQL for PHP
   yum: name=mysql state=present

 - name: 3. start Apache
   service: name=httpd state=started enabled=yes
