# Call Dockerfile
- template:
    src: Dockerfile.j2
    dest: /etc/Dockerfile
    mode: 0644
    owner: root
    group: root

- name: Build Docker file
  shell: docker build -t lamp:latest .
  args:
    chdir: /etc/

# Login Docker hub
- name: Log into DockerHub
  docker_login:
    username: prateeksw05
    password: pass1234
    reauthorize: yes

- name: Running the container
  docker_container:
    image: lamp:latest
    name: lamp
    state: started

- name: Push image into dokcer hub
  docker_image:
    name: lamp
    repository: prateeksw05/lamp:latest
    push: yes
